name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - name: Install Z-zip
        run: sudo apt-get install p7zip-full
      - name: Build
        run: ./make.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Flier.7z
          path: target/Flier.7z